//STREAK
export const GET_STREAK = "GET_STREAK";
export const GET_STREAK_SUCCESS = "GET_STREAK_SUCCESS";
export const GET_STREAK_FAIL = "GET_STREAK_FAIL";

export const GET_A_STREAK = "GET_A_STREAK";

export const CREATE_STREAK = "CREATE_STREAK";
export const CREATE_STREAK_SUCCESS = "CREATE_STREAK_SUCCESS";
export const CREATE_STREAK_FAIL = "CREATE_STREAK_FAIL";

export const UPDATE_STREAK = "UPDATE_STREAK";
export const UPDATE_STREAK_SUCCESS = "UPDATE_STREAK_SUCCESS";
export const UPDATE_STREAK_FAIL = "UPDATE_STREAK_FAIL";

export const DELETE_STREAK = "DELETE_STREAK";
export const DELETE_STREAK_SUCCESS = "DELETE_STREAK_SUCCESS";
export const DELETE_STREAK_FAIL = "DELETE_STREAK_FAIL";

export const STREAK_LIST_TYPE = "STREAK_LIST_TYPE";

//STREAK DETAILS
export const GET_STREAK_DETAIL = "GET_STREAK_DETAIL";
export const GET_STREAK_DETAIL_SUCCESS = "GET_STREAK_DETAIL_SUCCESS";
export const GET_STREAK_DETAIL_FAIL = "GET_STREAK_DETAIL_FAIL";

export const EMPTY_STREAK_DETAIL = "EMPTY_STREAK_DETAIL";

//REWARDS
export const CREATE_REWARD = 'CREATE_REWARD';
export const CREATE_REWARD_SUCCESS = 'CREATE_REWARD_SUCCESS';

export const GET_REWARDS = 'GET_REWARDS';
export const GET_REWARDS_SUCCESS = 'GET_REWARDS_SUCCESS';
export const GET_REWARDS_FAIL = 'GET_REWARDS_FAIL';

//ACTIVIIES
export const GET_ACTIVITIES = "GET_ACTIVITIES";
export const GET_ACTIVITIES_SUCCESS = "GET_ACTIVITIES_SUCCESS";
export const GET_ACTIVITIES_FAIL = "GET_ACTIVITIES_FAIL";

//USER
export const AUTH = 'AUTH';
export const LOGOUT = 'LOGOUT';
export const REFRESH_TOKEN = 'REFRESH_TOKEN';
export const SIGNIN_FAIL = 'SIGNIN_FAIL';

export const VERIFY_EMAIL = 'VERIFY_EMAIL';

//SEARCH 
export const SEARCH = 'SEARCH';

//PAYMAENT
export const PAYMENT_REQUEST = 'PAYMENT_REQUEST';
export const PAYMENT_REQUEST_FAIL = 'PAYMENT_REQUEST_FAIL';

//COMMON
export const STOP_LOADING = 'STOP_LOADING';
export const EMPTY_ERROR = 'EMPTY_ERROR';
export const ERROR = 'ERROR';