//STREAK
export const GET_STREAK = "GET_STREAK";
export const GET_STREAK_SUCCESS = "GET_STREAK_SUCCESS";
export const GET_STREAK_FAIL = "GET_STREAK_FAIL";

//STREAK
export const GET_ACTIVITIES = "GET_ACTIVITIES";
export const GET_ACTIVITIES_SUCCESS = "GET_ACTIVITIES_SUCCESS";
export const GET_ACTIVITIES_FAIL = "GET_ACTIVITIES_FAIL";

export const CREATE_STREAK = "CREATE_STREAK";
export const CREATE_STREAK_SUCCESS = "CREATE_STREAK_SUCCESS";
export const CREATE_STREAK_FAIL = "CREATE_STREAK_FAIL";

export const UPDATE_STREAK = "UPDATE_STREAK";
export const UPDATE_STREAK_SUCCESS = "UPDATE_STREAK_SUCCESS";
export const UPDATE_STREAK_FAIL = "UPDATE_STREAK_FAIL";

export const DELETE_STREAK = "DELETE_STREAK";
export const DELETE_STREAK_SUCCESS = "DELETE_STREAK_SUCCESS";
export const DELETE_STREAK_FAIL = "DELETE_STREAK_FAIL";

export const GET_STREAK_DETAIL = "GET_STREAK_DETAIL";
export const EMPTY_STREAK_DETAIL = "EMPTY_STREAK_DETAIL";

//REWARDS
export const GET_REWARDS = 'GET_REWARDS';
export const GET_REWARDS_SUCCESS = 'GET_REWARDS_SUCCESS';
export const GET_REWARDS_FAIL = 'GET_REWARDS_FAIL';

//USER
export const AUTH = 'AUTH';
export const LOGOUT = 'LOGOUT';